### ISSUE TITLE
rare segfault

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#6]
This happened only after a whole morning of testing, at the end of the longest/most successful session I had (~10 complex web pages loaded).

[14:09:45] [Flow 232] establishTLStoDecoy() failed with read tcp 192.168.99.26:42026->192.122.190.104:443: read: connection reset by peer
[14:09:45] [Flow 232] Shut down with error: read tcp 192.168.99.26:42026->192.122.190.104:443: read: connection reset by peer
[14:09:45] [Flow 233] establishTLStoDecoy() failed with read tcp 192.168.99.26:42028->192.122.190.104:443: read: connection reset by peer
[14:09:45] [Flow 233] Shut down with error: read tcp 192.168.99.26:42028->192.122.190.104:443: read: connection reset by peer
[14:09:45] [Flow 235] establishTLStoDecoy() failed with read tcp 192.168.99.26:42030->192.122.190.104:443: read: connection reset by peer
[14:09:45] [Flow 235] Shut down with error: read tcp 192.168.99.26:42030->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 236] establishTLStoDecoy() failed with read tcp 192.168.99.26:42136->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 236] Shut down with error: read tcp 192.168.99.26:42136->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 127] TapDance station didn't pick up the request. :(
[14:09:46] [Flow 127] Shut down with error: read tcp 192.168.99.26:40336->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 237] establishTLStoDecoy() failed with read tcp 192.168.99.26:42162->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 237] Shut down with error: read tcp 192.168.99.26:42162->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 238] establishTLStoDecoy() failed with read tcp 192.168.99.26:42164->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 238] Shut down with error: read tcp 192.168.99.26:42164->192.122.190.104:443: read: connection reset by peer
[14:09:46] [Flow 21] Connected to decoy tapdance1.freeaeskey.xyz
[14:09:47] [Flow 21] Successfully connected to Tapdance Station!
[14:09:47] [Flow 202] Closed gracefully.
[14:09:47] [Flow 33] establishTLStoDecoy() failed with read tcp 192.168.99.26:42193->192.122.190.104:443: read: connection reset by peer
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5087d4]

goroutine 144 [running]:
panic(0x74fdc0, 0xc82000a140)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/zmap/zgrab/ztools/ztls.(*Conn).Handshake(0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/zmap/zgrab/ztools/ztls/conn.go:1033 +0x1d4
github.com/zmap/zgrab/ztools/ztls.(*Conn).Read(0x0, 0xc8206c6100, 0x4034, 0x4034, 0x0, 0x0, 0x0)
        /home/fred/code/go/src/github.com/zmap/zgrab/ztools/ztls/conn.go:953 +0x6c
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).read_as(0xc820144180, 0xc8206a2300, 0x4034, 0x4034, 0x0, 0x0, 0x7f5422aeac28, 0xc8203d18b0)
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:214 +0x1af
github.com/SergeyFrolov/gotapdance/tapdance.(*tapdanceConn).Read(0xc820144180, 0xc820970200, 0x4034, 0x4034, 0x4034, 0x0, 0x0)
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/tdConn.go:177 +0xbe
github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect.func1()
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:58 +0xd8
created by github.com/SergeyFrolov/gotapdance/tapdance.(*TapDanceFlow).Redirect
        /home/fred/code/go/src/github.com/SergeyFrolov/gotapdance/tapdance/flow.go:100 +0x308

**Comment by SergeyFrolov** [comment]
Thanks for the report!
I believe I found the solution and will push it shortly.
